# GitHub Actions CI for carrardt/h264-tools fork
name: Build Windows Executables

on:
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest

    defaults:
      run:
        shell: msys2 {0}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up MSYS2
      uses: msys2/setup-msys2@v3
      with:
        update: true
        install: >-
          git
          mingw-w64-x86_64-toolchain
          mingw-w64-x86_64-cmake
          make

    - name: Create build directory
      run: mkdir -p build

    - name: Configure project
      run: cmake -G "MinGW Makefiles" -S . -B build

    - name: Build
      run: cmake --build build -- -j$(nproc)

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: h264-tools-windows
        path: build/*.exe
